#!/bin/sh
# Rebuilds Debian images

ARTIFACTS_DIR=${DEBIMG_ARTIFACTS_DIR:-/tmp/debimg/artifacts}
LOG_DIR=${DEBIMG_LOG_DIR:-/tmp/debimg/log}

docker build -t debimg .

mkdir -p /tmp/debimg/artifacts || exit
mkdir -p /tmp/debimg/log || exit

D=$(mktemp -d -p "${LOG_DIR}" rebuild-debians-XXXXXX)

IFS=,
grep -vE "^#|^\s*$" debians.csv | tail -n +2 | while read OS DIST ARCH _
do
    docker run --rm \
               -v "${ARTIFACTS_DIR}":/artifacts \
               --privileged \
               debimg \
               build-debian "${OS}" "${ARCH}" "${DIST}" \
               >"${D}"/"log-${OS}-${DIST}-${ARCH}.txt" 2>&1 &&
    rm "${D}"/"log-${OS}-${DIST}-${ARCH}.txt"
done
unset IFS
