#!/bin/sh
# Rebuild everything

DOCKEROPTS1="--rm -v /tmp/artifacts:/artifacts"
DOCKEROPTS2="--privileged $DOCKEROPTS1"

mkdir -p /tmp/artifacts || exit

# Build Docker image
docker build -t debimg .

# Build bootloaders
docker run $DOCKEROPTS1 debimg build-boot-allwinner "/artifacts/boot-bananapi" "Bananapi_defconfig" "arm-linux-gnueabihf"

# Build root filesystems
docker run $DOCKEROPTS2 debimg build-debian "/artifacts/debian-buster-armhf" "armhf" "buster"
