#!/bin/sh
# Rebuilds Debian images

ARTIFACTS_DIR=${DEBIMG_ARTIFACTS_DIR:-/tmp/debimg/artifacts}

docker build -t debimg .

mkdir -p /tmp/debimg/artifacts || exit

IFS=,
grep -vE "^#|^\s*$" debians.csv | while read DIST ARCH
do
    docker run --rm \
               -v "${ARTIFACTS_DIR}":/artifacts \
               --privileged \
               debimg \
               build-debian /artifacts/debian-"${DIST}"-"${ARCH}" "${ARCH}" "${DIST}"
done
unset IFS
