#!/bin/sh
# Build one debian image as part of a AWS Batch array job

ARRAY_S3_URI_BASE="${1}" # For example "s3://bucket/folder"
ARTIFACTS_S3_URI_BASE="${2}" # For example "s3://bucket/folder"

set -ex

ARGS=$(mktemp --tmpdir args-XXXXXX.sh)
trap 'rm -f "${ARGS}"' EXIT INT TERM

# Download parameters for this run
aws s3 cp "${ARRAY_S3_URI_BASE}/${AWS_BATCH_JOB_ARRAY_INDEX}" "${ARGS}"

# Source parameters
. "${ARGS}"

build-debian "${OS}" "${ARCH}" "${DIST}"

# Upload artifacts from this run
aws s3 cp "${ARTIFACTS_DIR:-/artifacts}" "${ARTIFACTS_S3_URI_BASE}" --recursive
