#!/bin/sh
# Generate initrd.uimg and update U-Boot boot.scr

# Kernel ABI string
ABI="${1}"

# Create U-Boot ramdisk image
mkimage -A arm -T ramdisk -C none -d "/boot/initrd.img-${ABI}" "/boot/initrd.uimg-${ABI}"

# Create U-Boot boot script
cat << EOF > /boot/boot.cmd
mmc dev 0
ext4load mmc 0:2 \${kernel_addr_r} /boot/vmlinuz-${ABI}
ext4load mmc 0:2 \${ramdisk_addr_r} /boot/initrd.uimg-${ABI}
ext4load mmc 0:2 \${fdt_addr_r} /usr/lib/linux-image-${ABI}/\${fdtfile}
setenv bootargs "root=/dev/mmcblk0p2 rw rootwait"
bootz \${kernel_addr_r} \${ramdisk_addr_r} \${fdt_addr_r}
EOF

# Create U-Boot boot script
mkimage -A arm -T script -C none -d /boot/boot.cmd /boot/boot.scr
