name: Rebuild debian.csv

on:
  schedule:
    # Every Sunday evening
    - cron: "00 21 * * 0"

jobs:
  rebuild-debian-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Rebuild
        timeout-minutes: 5
        run: |
          set -e
          git config user.name "Johan Gunnarsson"
          git config user.email "johan.gunnarsson@gmail.com"
          ./metascripts/rebuild-debian-csv
          git add debians.csv
          if git commit -m "debians: Update Debian/Ubuntu versions"; then
            ./metascripts/rebuild-jekyll-boards
            git add -A docs
            if git commit -m "docs: Regenerate boards"; then
              git push origin
            fi
          fi
