name: Debian/Ubuntu build/test

on:
  push:
    # Always except for irrelevant changes
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '*.csv'
  pull_request:
    # Always except for irrelevant changes
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '*.csv'
  schedule:
    # Every Sunday morning
    - cron: "00 03 * * 0"

jobs:
  build-boot-armhf:
    runs-on: ubuntu-latest
    name: build boot armhf

    steps:
    - name: Install dependencies
      timeout-minutes: 5
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get --assume-yes \
                     --no-install-recommends \
                       install bc \
                               bison \
                               device-tree-compiler \
                               dosfstools \
                               e2fsprogs \
                               flex \
                               gcc \
                               gcc-arm-none-eabi \
                               gcc-arm-linux-gnueabihf \
                               git \
                               libgnutls28-dev \
                               libssl-dev \
                               make \
                               mtools \
                               parted \
                               pigz \
                               python3-dev \
                               python3-pkg-resources \
                               swig

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build qemu_arm_virt
      timeout-minutes: 5
      run: |
        env PATH=$GITHUB_WORKSPACE/scripts:$PATH \
            ARTIFACTS_DIR=$RUNNER_TEMP \
            U_BOOT_GIT_REV="v2023.07" \
            U_BOOT_GIT_URL="https://github.com/u-boot/u-boot.git" \
            build-boot qemu_arm_virt \
                       qemu-arm \
                       qemu_arm_defconfig \
                       arm-linux-gnueabihf

    - name: Upload qemu_arm_virt
      uses: actions/upload-artifact@v4
      with:
        name: boot-qemu_arm_virt.bin.gz
        path: ${{ runner.temp }}/boot-qemu_arm_virt.bin.gz
        retention-days: 1

  build-boot-arm64:
    runs-on: ubuntu-latest
    name: Build boot arm64

    steps:
    - name: Install dependencies
      timeout-minutes: 5
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get --assume-yes \
                     --no-install-recommends \
                     install bc \
                             bison \
                             device-tree-compiler \
                             dosfstools \
                             e2fsprogs \
                             flex \
                             gcc \
                             gcc-arm-none-eabi \
                             gcc-aarch64-linux-gnu \
                             git \
                             libgnutls28-dev \
                             libssl-dev \
                             make \
                             mtools \
                             parted \
                             pigz \
                             python3-dev \
                             python3-pkg-resources \
                             swig

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build qemu_aarch64_virt
      timeout-minutes: 5
      run: |
        env PATH=$GITHUB_WORKSPACE/scripts:$PATH \
            ARTIFACTS_DIR=$RUNNER_TEMP \
            U_BOOT_GIT_REV="v2023.07" \
            U_BOOT_GIT_URL="https://github.com/u-boot/u-boot.git" \
            build-boot qemu_aarch64_virt \
                       qemu-aarch64 \
                       qemu_arm64_defconfig \
                       aarch64-linux-gnu

    - name: Upload qemu_aarch64_virt
      uses: actions/upload-artifact@v4
      with:
        name: boot-qemu_aarch64_virt.bin.gz
        path: ${{ runner.temp }}/boot-qemu_aarch64_virt.bin.gz
        retention-days: 1

  test-debian-armhf:
    runs-on: ubuntu-24.04-arm
    needs: build-boot-armhf
    name: Build/test ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.suite }} (armhf)

    strategy:
      matrix:
        include:
          # Debian armhf
          - os: debian
            suite: bookworm
            arch: armhf
          - os: debian
            suite: trixie
            arch: armhf
          - os: debian
            suite: sid
            arch: armhf
      fail-fast: false

    steps:
    - name: Install dependencies
      timeout-minutes: 5
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get --assume-yes \
                     install ca-certificates \
                             debian-archive-keyring \
                             debootstrap \
                             dosfstools \
                             e2fsprogs \
                             parted \
                             pigz \
                             pwgen \
                             qemu-system-arm \
                             ssh \
                             sshpass \
                             ubuntu-keyring

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build ${{ matrix.suite }} ${{ matrix.arch }}
      timeout-minutes: 15
      run: |
        sudo env PATH=$GITHUB_WORKSPACE/scripts:$PATH \
                 ARTIFACTS_DIR=$RUNNER_TEMP \
                 build-debian ${{ matrix.os }} \
                              ${{ matrix.arch }} \
                              ${{ matrix.suite }}

    - name: Download qemu_arm_virt
      timeout-minutes: 5
      uses: actions/download-artifact@v4
      with:
        name: boot-qemu_arm_virt.bin.gz
        path: ${{ runner.temp }}

    - name: Test qemu_arm_virt + ${{ matrix.suite }} ${{ matrix.arch }}
      timeout-minutes: 15
      run: |
        sudo ./test/qemu.sh $RUNNER_TEMP/boot-qemu_arm_virt.bin.gz \
                            $RUNNER_TEMP/${{ matrix.os }}-${{ matrix.suite }}-${{ matrix.arch }}-*.bin.gz

  test-debian-arm64:
    runs-on: ubuntu-24.04-arm
    needs: build-boot-arm64
    name: Build/test ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.suite }} (arm64)

    strategy:
      matrix:
        include:
          # Debian arm64
          - os: debian
            suite: bookworm
            arch: arm64
          - os: debian
            suite: trixie
            arch: arm64
          - os: debian
            suite: sid
            arch: arm64
          # Ubuntu arm64
          - os: ubuntu
            arch: arm64
            suite: jammy
          - os: ubuntu
            suite: noble
            arch: arm64
      fail-fast: false

    steps:
    - name: Install dependencies
      timeout-minutes: 5
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get --assume-yes \
                     install ca-certificates \
                             debian-archive-keyring \
                             debootstrap \
                             dosfstools \
                             e2fsprogs \
                             parted \
                             pigz \
                             pwgen \
                             qemu-system-arm \
                             ssh \
                             sshpass \
                             ubuntu-keyring

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build ${{ matrix.suite }} ${{ matrix.arch }}
      timeout-minutes: 15
      run: |
        sudo env PATH=$GITHUB_WORKSPACE/scripts:$PATH \
                 ARTIFACTS_DIR=$RUNNER_TEMP \
                 build-debian ${{ matrix.os }} \
                              ${{ matrix.arch }} \
                              ${{ matrix.suite }}

    - name: Download qemu_aarch64_virt
      timeout-minutes: 5
      uses: actions/download-artifact@v4
      with:
        name: boot-qemu_aarch64_virt.bin.gz
        path: ${{ runner.temp }}

    - name: Test qemu_aarch64_virt + ${{ matrix.suite }} ${{ matrix.arch }}
      timeout-minutes: 15
      run: |
        sudo ./test/qemu.sh $RUNNER_TEMP/boot-qemu_aarch64_virt.bin.gz \
                            $RUNNER_TEMP/${{ matrix.os }}-${{ matrix.suite }}-${{ matrix.arch }}-*.bin.gz
